# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Ismc < Formula
  desc "Apple SMC CLI tool that can decode and display temperature, fans, battery, power, voltage and current information"
  homepage "https://github.com/dkorunic/iSMC"
  version "0.16.5"
  license "GPL-3.0"
  depends_on :macos

  url "https://github.com/dkorunic/iSMC/releases/download/v0.16.5/iSMC_Darwin_all.tar.gz"
  sha256 "bc41d966ebb20eabb8a97967b2952febf3fbf888c2174103e869379c8b6542d5"

  define_method(:install) do
    bin.install "iSMC"
  end

  test do
    system "#{bin}/iSMC", "help"
  end
end
