# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Ismc < Formula
  desc "Apple SMC CLI tool that can decode and display temperature, fans, battery, power, voltage and current information"
  homepage "https://github.com/dkorunic/iSMC"
  version "0.16.1"
  license "GPL-3.0"
  depends_on :macos

  url "https://github.com/dkorunic/iSMC/releases/download/v0.16.1/iSMC_Darwin_all.tar.gz"
  sha256 "87ba5442741ad83afee1a43222cfb1c1f1f4a27e8d700a83662253f9d43c9624"

  define_method(:install) do
    bin.install "iSMC"
  end

  test do
    system "#{bin}/iSMC", "help"
  end
end
