# This file was generated by GoReleaser. DO NOT EDIT.
cask "astro-recommender" do
  version "0.10.1"

  on_macos do
    url "https://github.com/dkorunic/astro-recommender/releases/download/v#{version}/astro-recommender_Darwin_all.tar.gz"
    sha256 "22b7489939fca99f256f9f669a8198d8604952f392bb1784ca510604114e1e8d"
  end

  on_linux do
    on_intel do
      url "https://github.com/dkorunic/astro-recommender/releases/download/v#{version}/astro-recommender_Linux_x86_64.tar.gz"
      sha256 "92e1ff8299c17dc8cd6e78acef833407505031db7a588893f8caff19c809137a"
    end
    on_arm do
      url "https://github.com/dkorunic/astro-recommender/releases/download/v#{version}/astro-recommender_Linux_arm64.tar.gz"
      sha256 "fa8182dd260e3d4247f796683ad3ca61f938f135934eb5a6502ec3128d74919a"
    end
  end

  name "astro-recommender"
  desc "Ranks deep sky objects and bright comets to image tonight from a given location"
  homepage "https://github.com/dkorunic/astro-recommender"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "astro-recommender"

  postflight do
    if system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/astro-recommender"]
    end
  end

  # No zap stanza required

end
