# This file was generated by GoReleaser. DO NOT EDIT.
cask "astro-recommender" do
  version "0.13.0"

  on_macos do
    url "https://github.com/dkorunic/astro-recommender/releases/download/v#{version}/astro-recommender_Darwin_all.tar.gz"
    sha256 "e3a08f6f4439ff6d54476dde385fa4abac49cb7961f5ac974690beb5eb4c02ee"
  end

  on_linux do
    on_intel do
      url "https://github.com/dkorunic/astro-recommender/releases/download/v#{version}/astro-recommender_Linux_x86_64.tar.gz"
      sha256 "162eaf813fce289418b60c44eef1a87e9ee199eed37ed1ca5d1ac2178044c323"
    end
    on_arm do
      url "https://github.com/dkorunic/astro-recommender/releases/download/v#{version}/astro-recommender_Linux_arm64.tar.gz"
      sha256 "562ecb1cb51a68dfc2ef849bcb0bcd02e4a992827f3c02f2765e6c5dcee48643"
    end
  end

  name "astro-recommender"
  desc "Ranks deep sky objects and bright comets to image tonight from a given location"
  homepage "https://github.com/dkorunic/astro-recommender"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "astro-recommender"

  postflight do
    if system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/astro-recommender"]
    end
  end

  # No zap stanza required

end
