# This file was generated by GoReleaser. DO NOT EDIT.
cask "astro-recommender" do
  version "0.7.1"

  on_macos do
    url "https://github.com/dkorunic/astro-recommender/releases/download/v#{version}/astro-recommender_Darwin_all.tar.gz"
    sha256 "744cedc1adbab94768d12497bd6d77f16d8a55b1427f2b9474c46138f2974004"
  end

  on_linux do
    on_intel do
      url "https://github.com/dkorunic/astro-recommender/releases/download/v#{version}/astro-recommender_Linux_x86_64.tar.gz"
      sha256 "4e1afdb5dc7d3edd8bea967dd8860e60bfd3bbcaef20b832a93b6176a07a7175"
    end
    on_arm do
      url "https://github.com/dkorunic/astro-recommender/releases/download/v#{version}/astro-recommender_Linux_arm64.tar.gz"
      sha256 "1c619f91c6ae356a0954a7b3a00fe4af3808019670d5e3dcf5b11080d93161ba"
    end
  end

  name "astro-recommender"
  desc "Ranks deep sky objects and bright comets to image tonight from a given location"
  homepage "https://github.com/dkorunic/astro-recommender"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "astro-recommender"

  postflight do
    if system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/astro-recommender"]
    end
  end

  # No zap stanza required

end
