# This file was generated by GoReleaser. DO NOT EDIT.
cask "ismc" do
  version "0.17.2"

  on_macos do
    url "https://github.com/dkorunic/iSMC/releases/download/v#{version}/iSMC_Darwin_all.tar.gz"
    sha256 "06933bbc1d9428be5f49ea393a275649c589c670282227bb54358d2f47f62541"
  end

  name "ismc"
  desc "Apple SMC CLI tool that can decode and display temperature, fans, battery, power, voltage and current information"
  homepage "https://github.com/dkorunic/iSMC"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "iSMC"

  postflight do
    if system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/iSMC"]
    end
  end

  # No zap stanza required

end
