# This file was generated by GoReleaser. DO NOT EDIT.
cask "ismc" do
  version "0.16.6"

  on_macos do
    url "https://github.com/dkorunic/iSMC/releases/download/v#{version}/iSMC_Darwin_all.tar.gz"
    sha256 "e3e43f8bef1521127a71010851976371f1261bf0fb9da0c3a3aaa707bff7466b"
  end

  name "ismc"
  desc "Apple SMC CLI tool that can decode and display temperature, fans, battery, power, voltage and current information"
  homepage "https://github.com/dkorunic/iSMC"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "iSMC"

  postflight do
    if system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/iSMC"]
    end
  end

  # No zap stanza required

end
