# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Ismc < Formula
  desc "Apple SMC CLI tool that can decode and display temperature, fans, battery, power, voltage and current information"
  homepage "https://github.com/dkorunic/iSMC"
  version "0.17.4"
  license "GPL-3.0"
  depends_on :macos

  url "https://github.com/dkorunic/iSMC/releases/download/v0.17.4/iSMC_Darwin_all.tar.gz"
  sha256 "d5c9bf322733550cdd81a32dc338c5cc7f5156edeb65c9c938635757bc797331"

  define_method(:install) do
    bin.install "iSMC"
  end

  test do
    system "#{bin}/iSMC", "help"
  end
end
