# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Ismc < Formula
  desc "Apple SMC CLI tool that can decode and display temperature, fans, battery, power, voltage and current information"
  homepage "https://github.com/dkorunic/iSMC"
  version "0.17.0"
  license "GPL-3.0"
  depends_on :macos

  url "https://github.com/dkorunic/iSMC/releases/download/v0.17.0/iSMC_Darwin_all.tar.gz"
  sha256 "26eab3862a419f21f2ec5baca0009e3891b6b0067dd8d6fcd735e646f8aeb911"

  define_method(:install) do
    bin.install "iSMC"
  end

  test do
    system "#{bin}/iSMC", "help"
  end
end
